# Documentación Redirección http-https:
# https://doc.traefik.io/traefik/migration/v1-to-v2/#http-to-https-redirection-is-now-configured-on-routers
# código ejemplo:
# https://www.youtube.com/watch?v=naCHq6sMMI8

version: "3.3"

services:


  proxy:
    image: opendx/nginx
    build:
      context: ./proxy
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    #      - ./proxy/web/index.html:/usr/share/nginx/htmDCl/index.html
    command: [ nginx-debug, '-g', 'daemon off;' ]

  3dslicer-hub:
    image: opendx/tslicerh
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./tsliceh:/app/tsliceh:ro
      - /var/run/docker.sock:/var/run/docker.sock

#  slicer_1:
#    image: stevepieper/slicer-chronicle:4.10.2
#    volumes:
#      - slicer-storage_1:/var/cache/apt
#    ports:
#      - "8080:8080"
#    expose:
#      - "8080"
